<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';
$test = ComposerAutoloaderInit9bfda01c7369435c944144875d16f9a8::getLoader();;
// var_dump($test);exit();
return $test;
